import type { ValidationRecord } from "../types.ts";

export const sampleValidations: ValidationRecord[] = [
  {
    id: "1",
    tweetId: "1927914891702083761",
    tweetAuthor: "Elon Musk",
    tweetAuthorHandle: "elonmusk",
    requestedBy: "Alice Smith",
    requestedByHandle: "alice",
    timestamp: new Date(Date.now() - 2 * 60 * 1000).toISOString(), // 2 minutes ago
    tweetUrl: "https://x.com/elonmusk/status/1927914891702083761",
    engagementStats: {
      total_retweeters: 127,
      total_repliers: 45,
      total_quote_tweeters: 23,
      total_unique_users: 195,
      reputable_retweeters: 108,
      reputable_repliers: 38,
      reputable_quote_tweeters: 19,
      reputable_total: 165,
      reputable_percentage: 85,
      retweeters_rate_limited: false,
      repliers_rate_limited: false,
      quote_tweeters_rate_limited: false,
    },
    overallQuality: "high",
  },
  {
    id: "2",
    tweetId: "1927888123456789012",
    tweetAuthor: "SuspiciousBot",
    tweetAuthorHandle: "bot_account",
    requestedBy: "Bob Johnson",
    requestedByHandle: "bob",
    timestamp: new Date(Date.now() - 5 * 60 * 1000).toISOString(), // 5 minutes ago
    tweetUrl: "https://x.com/bot_account/status/1927888123456789012",
    engagementStats: {
      total_retweeters: 2100,
      total_repliers: 150,
      total_quote_tweeters: 75,
      total_unique_users: 2325,
      reputable_retweeters: 252,
      reputable_repliers: 18,
      reputable_quote_tweeters: 9,
      reputable_total: 279,
      reputable_percentage: 12,
      retweeters_rate_limited: true,
      repliers_rate_limited: false,
      quote_tweeters_rate_limited: false,
    },
    overallQuality: "low",
  },
  {
    id: "3",
    tweetId: "1927777987654321098",
    tweetAuthor: "Vitalik Buterin",
    tweetAuthorHandle: "vitalik",
    requestedBy: "Charlie Wilson",
    requestedByHandle: "charlie",
    timestamp: new Date(Date.now() - 8 * 60 * 1000).toISOString(), // 8 minutes ago
    tweetUrl: "https://x.com/vitalik/status/1927777987654321098",
    engagementStats: {
      total_retweeters: 89,
      total_repliers: 67,
      total_quote_tweeters: 34,
      total_unique_users: 190,
      reputable_retweeters: 38,
      reputable_repliers: 29,
      reputable_quote_tweeters: 15,
      reputable_total: 82,
      reputable_percentage: 43,
      retweeters_rate_limited: false,
      repliers_rate_limited: false,
      quote_tweeters_rate_limited: false,
    },
    overallQuality: "medium",
  },
  {
    id: "4",
    tweetId: "1927666543210987654",
    tweetAuthor: "Coinbase",
    tweetAuthorHandle: "coinbase",
    requestedBy: "David Brown",
    requestedByHandle: "dave",
    timestamp: new Date(Date.now() - 12 * 60 * 1000).toISOString(), // 12 minutes ago
    tweetUrl: "https://x.com/coinbase/status/1927666543210987654",
    engagementStats: {
      total_retweeters: 445,
      total_repliers: 123,
      total_quote_tweeters: 89,
      total_unique_users: 657,
      reputable_retweeters: 347,
      reputable_repliers: 96,
      reputable_quote_tweeters: 69,
      reputable_total: 512,
      reputable_percentage: 78,
      retweeters_rate_limited: false,
      repliers_rate_limited: false,
      quote_tweeters_rate_limited: false,
    },
    overallQuality: "high",
  },
]; 